name = "ProjetMIR"
seed = 42

[data]
path = "data/"

[model.mlp]
sliding_window_size = 51 # size of the context window
precision = "full" # precision for the models weights

[training.mlp]
batch_size = 32
epoch = 5
with_split = 0.8 # train / test split
shuffle = true # to shuffle in the dataloader
loss = "cross_entropy"
optimizer = "adam"
weight_decay = 0.01
lr = 1e-3
