name = "ProjetMIR"
seed = 38 # 42
train = "xgboost"
result_file = "results.md"
log_file = "log.md"
not_below = 255 # cut the signal of length below this value


[data]
path = "data/"
num_workers = 2 # num workers for the dataloader cf pytorch doc

[model.mlp]
sliding_window_size = 51 # size of the context window
precision = "full" # precision for the models weights

[training.mlp]
stop = 4096
batch_size = 32
epoch = 5
with_split = 0.8 # train / test split
shuffle = true # to shuffle in the dataloader
loss = "cross_entropy"
loss_weight = true
optimizer = "adam"
weight_decay = 0.01
lr = 1e-3


[model.unet]
sliding_window_size = 256  # size of the context window / !!  Mandatory : Must be a 16 multiple to match dimension crop and increase in the Unet !!
precision = "full" # precision for the models weights
padding = 1 

[training.unet]
stop = 512
batch_size = 32
epoch = 18
with_split = 0.8 # train / test split
shuffle = true # to shuffle in the dataloader
loss = "cross_entropy"
loss_weight = false
optimizer = "adam"
weight_decay = 0.01
lr = 1e-3

[model.xgboost]
sliding_window_size = 256

[training.xgboost]
stop = 512
with_split = 0.8
n_estimators = 1000
max_depth = 7
learning_rate = 0.05
subsample = 0.8514
colsample_bytree = 0.6923
